parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            ReadModel:
                is_bundle: false
                type: xml
                dir: '%kernel.root_dir%/Resources/config/doctrine'
                prefix: 'App\Infrastructure\ReadModel'
                alias: ReadModel

services:
    _defaults:
        public: true

    # Repositories
    App\Application\Group\Repository\Groups: '@App\Infrastructure\Repository\EventStoreGroups'
    App\Application\Idea\Repository\Ideas: '@App\Infrastructure\Repository\EventStoreIdeas'
    App\Application\Comment\Repository\Comments: '@App\Infrastructure\Repository\EventStoreComments'

    App\Infrastructure\ReadModel\Group\Repository\GroupViews: '@App\Infrastructure\Doctrine\Repository\GroupViewORMRepository'
