parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            ReadModel:
                is_bundle: false
                type: 'xml'
                dir: '%kernel.root_dir%/Resources/config/doctrine'
                prefix: 'AulaSoftwareLibre\Gata\Infrastructure\ReadModel\View'
                alias: 'ReadModel'

services:
    _defaults:
        public: true

    # Repositories
    AulaSoftwareLibre\Gata\Application\Group\Repository\Groups: '@AulaSoftwareLibre\Gata\Infrastructure\Doctrine\EventStore\GroupsEventStore'
    AulaSoftwareLibre\Gata\Application\Idea\Repository\Ideas: '@AulaSoftwareLibre\Gata\Infrastructure\Doctrine\EventStore\IdeasEventStore'
    AulaSoftwareLibre\Gata\Application\Comment\Repository\Comments: '@AulaSoftwareLibre\Gata\Infrastructure\Doctrine\EventStore\CommentsEventStore'

    AulaSoftwareLibre\Gata\Infrastructure\ReadModel\Repository\GroupViews: '@AulaSoftwareLibre\Gata\Infrastructure\Doctrine\Repository\GroupViewORMRepository'
