prooph_event_store:
    stores:
        default:
            event_store: 'Prooph\EventStore\Pdo\PostgresEventStore'
            repositories:
                AulaSoftwareLibre\Gata\Infrastructure\Repository\EventStoreGroups:
                    aggregate_type: 'AulaSoftwareLibre\Gata\Domain\Group\Model\Group'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
                AulaSoftwareLibre\Gata\Infrastructure\Repository\EventStoreIdeas:
                    aggregate_type: 'AulaSoftwareLibre\Gata\Domain\Idea\Model\Idea'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
                AulaSoftwareLibre\Gata\Infrastructure\Repository\EventStoreComments:
                    aggregate_type: 'AulaSoftwareLibre\Gata\Domain\Comment\Model\Comment'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'


