version: '3'
services:
    database:
        image: 'postgres:9'
        ports:
            - '5432'
        volumes:
            - './vendor/prooph/pdo-event-store/scripts/postgres:/docker-entrypoint-initdb.d'
            - './var/run/postgresql:/run/postgresql'
        environment:
            - 'POSTGRES_USER=gata'
            - 'POSTGRES_PASSWORD'

    group_projection:
        build: 'docker/php'
        entrypoint:
            - '/app/.docker/wait-for-postgres.sh'
        volumes:
            - '.:/app'
        depends_on:
            - 'database'
        environment:
            - 'DATABASE_URL'
        command: 'php bin/console event-store:projection:run group_projection'
